package com.mvr.poliza.utils;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ResponseMessage {
    MESSAGE_OK("OK"),
    ACTUALIZAR_POLIZA("SE ACTUALIZO CORRECTAMENTE LA POLIZA"),
    ELIMINAR_POLIZA("SE ELIMINO CORRECTAMENTE LA POLIZA"),
    ACTUALIZAR_FALLO("HA OCURRIDO UN ERROR AL INTENTAR ACTUALIZAR LA POLIZA"),
    CONSULTA_FALLO("HA OCURRIDO UN ERROR AL CONSULTAR LA POLIZA"),
    GRABAR_FALLO("HA OCURRIDO UN ERRO EN LOS GRABADOS DE LA POLIZA"),
    ELIMINAR_FALLO("HA OCURRIDO UN ERROR AL INTENTAR ELIMINAR LA POLIZA"),
    EMPLEADO_NO_EXISTE("EL EMPLEADO NO EXISTE"),
    ARTICULO_NO_EXISTE("EL ARTICULO NO EXISTE"),
    CANTIDAD("LA CANTIDAD DE LA POLIZA ES MAYOR QUE LA CANTIDAD DEL ARTICULO"),
    ERROR_CANTIDAD("NO HAY SUFICIENTES ARTICULOS");
    
    private final String msgInformativo;
}
